#pragma once
#include "pch/pch.h"

namespace tables {
	enum class eSessionType : i32 {
		Public,
		NewPublic,
		ClosedCrew,
		Crew,
		ClosedFriend = 6,
		FindFriend = 9,
		Solo,
		InviteOnly,
		JoinCrew,
		SCTV,
		Leave = -1
	};
	struct SessionType {
		eSessionType type{};
		cc id[22]{};
		cc name[22]{};
	};
	inline constexpr SessionType g_sessions[]{
		{ eSessionType::Public, "public", "Public" },
		{ eSessionType::NewPublic, "new public", "New Public" },
		{ eSessionType::ClosedCrew, "closed crew", "Closed Crew" },
		{ eSessionType::Crew, "crew", "Crew" },
		{ eSessionType::ClosedFriend, "closed friend", "Closed Friend" },
		{ eSessionType::FindFriend, "friends", "Find Friends" },
		{ eSessionType::Solo, "solo", "Solo" },
		{ eSessionType::InviteOnly, "invite", "Invite-Only" },
		{ eSessionType::JoinCrew, "join crew", "Join Crewmates" },
		{ eSessionType::SCTV, "admin", "SCTV" },
		{ eSessionType::Leave, "leave", "Leave" },
	};
}
namespace datanodes {
	inline std::vector<std::pair<u32, std::vector<u32>>> g_syncTrees = {
		{
			"CAutomobileSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CAutomobileCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CBikeSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CBikeGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CBoatSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CBoatGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CDoorSyncTree"_joaat, {
				"CDoorCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDoorScriptInfoDataNode"_joaat,
				"CDoorScriptGameStateDataNode"_joaat,
				"CDoorMovementDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat
			}
		},
		{
			"CHeliSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CAutomobileCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CHeliHealthDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CHeliControlDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CObjectSyncTree"_joaat, {
				"CObjectCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CObjectGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CObjectScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CPhysicalHealthDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CObjectSectorPosNode"_joaat,
				"CObjectOrientationNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CPhysicalAngVelocityDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat
			}
		},
		{
			"CPedSyncTree"_joaat, {
				"CPedCreationDataNode"_joaat,
				"CPedScriptCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CPedGameStateDataNode"_joaat,
				"CPedComponentReservationDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CPedScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPedAttachDataNode"_joaat,
				"CPedHealthDataNode"_joaat,
				"CPedMovementGroupDataNode"_joaat,
				"CPedAIDataNode"_joaat,
				"CPedAppearanceDataNode"_joaat,
				"CPedOrientationDataNode"_joaat,
				"CPedMovementDataNode"_joaat,
				"CPedTaskTreeDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CPedSectorPosMapNode"_joaat,
				"CPedSectorPosNavMeshNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CPedInventoryDataNode"_joaat,
				"CPedTaskSequenceDataNode"_joaat
			}
		},
		{
			"CPickupSyncTree"_joaat, {
				"CPickupCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPickupScriptGameStateNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalHealthDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CPickupSectorPosNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CPhysicalAngVelocityDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat
			}
		},
		{
			"CPickupPlacementSyncTree"_joaat, {
				"CPickupPlacementCreationDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CPickupPlacementStateDataNode"_joaat
			}
		},
		{
			"CPlaneSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CPlaneGameStateDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CPlaneControlDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CSubmarineSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CSubmarineGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CSubmarineControlDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CPlayerSyncTree"_joaat, {
				"CPlayerCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CPedGameStateDataNode"_joaat,
				"CPedComponentReservationDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPlayerGameStateDataNode"_joaat,
				"CPedAttachDataNode"_joaat,
				"CPedHealthDataNode"_joaat,
				"CPedMovementGroupDataNode"_joaat,
				"CPedAIDataNode"_joaat,
				"CPlayerAppearanceDataNode"_joaat,
				"CPlayerPedGroupDataNode"_joaat,
				"CPlayerAmbientModelStreamingNode"_joaat,
				"CPlayerGamerDataNode"_joaat,
				"CPlayerExtendedGameStateNode"_joaat,
				"CPedOrientationDataNode"_joaat,
				"CPedMovementDataNode"_joaat,
				"CPedTaskTreeDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CPedTaskSpecificDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CPlayerSectorPosNode"_joaat,
				"CPlayerCameraDataNode"_joaat,
				"CPlayerWantedAndLOSDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat
			}
		},
		{
			"CAutomobileSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CAutomobileCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
		{
			"CTrainSyncTree"_joaat, {
				"CVehicleCreationDataNode"_joaat,
				"CGlobalFlagsDataNode"_joaat,
				"CDynamicEntityGameStateDataNode"_joaat,
				"CPhysicalGameStateDataNode"_joaat,
				"CVehicleGameStateDataNode"_joaat,
				"CTrainGameStateDataNode"_joaat,
				"CEntityScriptGameStateDataNode"_joaat,
				"CPhysicalScriptGameStateDataNode"_joaat,
				"CVehicleScriptGameStateDataNode"_joaat,
				"CEntityScriptInfoDataNode"_joaat,
				"CPhysicalAttachDataNode"_joaat,
				"CVehicleAppearanceDataNode"_joaat,
				"CVehicleDamageStatusDataNode"_joaat,
				"CVehicleComponentReservationDataNode"_joaat,
				"CVehicleHealthDataNode"_joaat,
				"CVehicleTaskDataNode"_joaat,
				"CSectorDataNode"_joaat,
				"CSectorPositionDataNode"_joaat,
				"CEntityOrientationDataNode"_joaat,
				"CPhysicalVelocityDataNode"_joaat,
				"CVehicleAngVelocityDataNode"_joaat,
				"CVehicleSteeringDataNode"_joaat,
				"CVehicleControlDataNode"_joaat,
				"CVehicleGadgetDataNode"_joaat,
				"CMigrationDataNode"_joaat,
				"CPhysicalMigrationDataNode"_joaat,
				"CPhysicalScriptMigrationDataNode"_joaat,
				"CVehicleProximityMigrationDataNode"_joaat
			}
		},
	};
	inline std::pair<u32, u64> g_nodes[81]{
		{ "CAutomobileCreationDataNode"_joaat, NULL },
		{ "CBikeGameStateDataNode"_joaat, NULL },
		{ "CBoatGameStateDataNode"_joaat, NULL },
		{ "CDoorCreationDataNode"_joaat, NULL },
		{ "CDoorMovementDataNode"_joaat, NULL },
		{ "CDoorScriptGameStateDataNode"_joaat, NULL },
		{ "CDoorScriptInfoDataNode"_joaat, NULL },
		{ "CDynamicEntityGameStateDataNode"_joaat, NULL },
		{ "CEntityOrientationDataNode"_joaat, NULL },
		{ "CEntityScriptGameStateDataNode"_joaat, NULL },
		{ "CEntityScriptInfoDataNode"_joaat, NULL },
		{ "CGlobalFlagsDataNode"_joaat, NULL },
		{ "CHeliControlDataNode"_joaat, NULL },
		{ "CHeliHealthDataNode"_joaat, NULL },
		{ "CMigrationDataNode"_joaat, NULL },
		{ "CObjectCreationDataNode"_joaat, NULL },
		{ "CObjectGameStateDataNode"_joaat, NULL },
		{ "CObjectOrientationNode"_joaat, NULL },
		{ "CObjectScriptGameStateDataNode"_joaat, NULL },
		{ "CObjectSectorPosNode"_joaat, NULL },
		{ "CPedAIDataNode"_joaat, NULL },
		{ "CPedAppearanceDataNode"_joaat, NULL },
		{ "CPedAttachDataNode"_joaat, NULL },
		{ "CPedComponentReservationDataNode"_joaat, NULL },
		{ "CPedCreationDataNode"_joaat, NULL },
		{ "CPedGameStateDataNode"_joaat, NULL },
		{ "CPedHealthDataNode"_joaat, NULL },
		{ "CPedInventoryDataNode"_joaat, NULL },
		{ "CPedMovementDataNode"_joaat, NULL },
		{ "CPedMovementGroupDataNode"_joaat, NULL },
		{ "CPedOrientationDataNode"_joaat, NULL },
		{ "CPedScriptCreationDataNode"_joaat, NULL },
		{ "CPedScriptGameStateDataNode"_joaat, NULL },
		{ "CPedSectorPosMapNode"_joaat, NULL },
		{ "CPedSectorPosNavMeshNode"_joaat, NULL },
		{ "CPedTaskSequenceDataNode"_joaat, NULL },
		{ "CPedTaskSpecificDataNode"_joaat, NULL },
		{ "CPedTaskTreeDataNode"_joaat, NULL },
		{ "CPhysicalAngVelocityDataNode"_joaat, NULL },
		{ "CPhysicalAttachDataNode"_joaat, NULL },
		{ "CPhysicalGameStateDataNode"_joaat, NULL },
		{ "CPhysicalHealthDataNode"_joaat, NULL },
		{ "CPhysicalMigrationDataNode"_joaat, NULL },
		{ "CPhysicalScriptGameStateDataNode"_joaat, NULL },
		{ "CPhysicalScriptMigrationDataNode"_joaat, NULL },
		{ "CPhysicalVelocityDataNode"_joaat, NULL },
		{ "CPickupCreationDataNode"_joaat, NULL },
		{ "CPickupPlacementCreationDataNode"_joaat, NULL },
		{ "CPickupPlacementStateDataNode"_joaat, NULL },
		{ "CPickupScriptGameStateNode"_joaat, NULL },
		{ "CPickupSectorPosNode"_joaat, NULL },
		{ "CPlaneControlDataNode"_joaat, NULL },
		{ "CPlaneGameStateDataNode"_joaat, NULL },
		{ "CPlayerAmbientModelStreamingNode"_joaat, NULL },
		{ "CPlayerAppearanceDataNode"_joaat, NULL },
		{ "CPlayerCameraDataNode"_joaat, NULL },
		{ "CPlayerCreationDataNode"_joaat, NULL },
		{ "CPlayerExtendedGameStateNode"_joaat, NULL },
		{ "CPlayerGameStateDataNode"_joaat, NULL },
		{ "CPlayerGamerDataNode"_joaat, NULL },
		{ "CPlayerPedGroupDataNode"_joaat, NULL },
		{ "CPlayerSectorPosNode"_joaat, NULL },
		{ "CPlayerWantedAndLOSDataNode"_joaat, NULL },
		{ "CSectorDataNode"_joaat, NULL },
		{ "CSectorPositionDataNode"_joaat, NULL },
		{ "CSubmarineControlDataNode"_joaat, NULL },
		{ "CSubmarineGameStateDataNode"_joaat, NULL },
		{ "CTrainGameStateDataNode"_joaat, NULL },
		{ "CVehicleAngVelocityDataNode"_joaat, NULL },
		{ "CVehicleAppearanceDataNode"_joaat, NULL },
		{ "CVehicleComponentReservationDataNode"_joaat, NULL },
		{ "CVehicleControlDataNode"_joaat, NULL },
		{ "CVehicleCreationDataNode"_joaat, NULL },
		{ "CVehicleDamageStatusDataNode"_joaat, NULL },
		{ "CVehicleGadgetDataNode"_joaat, NULL },
		{ "CVehicleGameStateDataNode"_joaat, NULL },
		{ "CVehicleHealthDataNode"_joaat, NULL },
		{ "CVehicleProximityMigrationDataNode"_joaat, NULL },
		{ "CVehicleScriptGameStateDataNode"_joaat, NULL },
		{ "CVehicleSteeringDataNode"_joaat, NULL },
		{ "CVehicleTaskDataNode"_joaat, NULL }
	};
}